# Generated by Django 4.2.2 on 2025-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_scheduledat_alter_article_updated'),
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_viewed_articles',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='articles.article'),
        ),
    ]
